name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-json:
    name: Validate JSON
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Sync deps
        run: uv sync --all-extras
      - name: Validate
        run: uv run python scripts/validate_json.py --strict

  lint-format:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Sync deps
        run: uv sync --all-extras
      - name: Ruff format check
        run: uv run ruff format --check .
      - name: Ruff lint
        run: uv run ruff check .

  type-check:
    name: Type Check (mypy --strict)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Sync deps
        run: uv sync --all-extras
      - name: Mypy strict (focused)
        run: |
          uv run mypy \
            scripts/rules \
            scripts/build_pipeline.py \
            dashboard/api \
            --strict --ignore-missing-imports

  test-unit:
    name: Tests (unit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Sync deps
        run: uv sync --all-extras
      - name: Run unit tests with coverage gate
        run: uv run pytest -m unit -q --cov=dashboard --cov=scripts --cov-branch --cov-report=xml --cov-fail-under=50
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-unit-xml
          path: coverage.xml

  test-integration:
    name: Tests (integration & others)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Sync deps
        run: uv sync --all-extras
      - name: Run integration/other tests with coverage gate
        run: uv run pytest -m "not unit" -q --cov=dashboard --cov=scripts --cov-branch --cov-report=xml --cov-fail-under=50
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-int-xml
          path: coverage.xml

  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [validate-json, lint-format, type-check, test-unit, test-integration]
    steps:
      - run: echo "All required jobs passed."
